---
title: "Osa Conservation: Movement data audit"

author:
  - Chris Beirne

site: bookdown::test-bookdown
output: bookdown::gitbook
documentclass: book
biblio-style: apalike
link-citations: yes
---

# Device Status

This document summarizes the movement locations for all active devices within Osa Conservation's movement ecology project. 

```{r c01, echo=F, message=F, include=F}
knitr::opts_chunk$set(echo = FALSE)

library(rgdal) 
library(move)
library(dplyr)
library(leaflet)
library(units)
library(sf)
library(viridis)
library(kableExtra)
library(lubridate)
library(plotly)
## Load packages for google drive ----
library(googledrive)
library(purrr)
library(readxl)
library(geosphere)
library(foreach)
library(maptools)

options(googledrive_quiet = TRUE)

# For when the trapping effort file is sorted
# googledrive::drive_auth(path = Sys.getenv("GOOGLE_AUTHENTICATION_CREDENTIALS"))
# 
# ## Find Google Drive folder 'Centre Circle Data & Info'
# data_folder <- drive_ls(path = "08 Databases + Analysis")
# data_path <- "data" 
# dir.create(data_path) 
# drive_download(as_id("14hLi94W4WbDn6jdXahJMnxllOgLpZh-PpIBOWqt9jlc"),
#                path="data/2_vulture_trap_deployments.xlsx")
#capture_dat <- read_excel("data/2_vulture_trap_deployments.xlsx")



# Import passcodes
MOVE_PASS <- Sys.getenv("MOVEBANK_PASSWORD")
MOVE_USE  <- Sys.getenv("MOVEBANK_USERNAME")

loginStored <- movebankLogin(username=MOVE_USE, 
                             password=MOVE_PASS)

# Get animals to check ID's in data
# Vultures
animals <-getMovebankAnimals(study=1573471517,login=loginStored)
# Ocelot
tmp <-getMovebankAnimals(study=2526574641,login=loginStored)
# Tapir
tmp2 <- getMovebankAnimals(study=1954804459,login=loginStored)
animals <- rbind(animals, tmp,tmp2)

# For some reason they are duplicated
animals[duplicated(animals)==F,]
# They vary by the field "sensor_type_id"
animals <- animals[animals$sensor_type_id==653 & is.na(animals$sensor_type_id)==F,]

# Clean up the name
animals$animalName <- paste0(sub('\\_.*', '', animals$animalName), "_", sub('\\ .*', '', animals$taxon_canonical_name))
animals$name <- sub('\\_.*', '', animals$animalName)
animals$name[animals$name=="Robin Hood"] <- "Robin.Hood"


# Sort date objects
animals$timestamp_start <- ymd_hms(animals$timestamp_start)
animals$timestamp_end <- ymd_hms(animals$timestamp_end)


drive_auth()
## Authenticate into googledrive service account ----
## 'GOOGLE_APPLICATION_CREDENTIALS' is what we named the Github Secret that 
## contains the credential JSON file
googledrive::drive_auth(path = Sys.getenv("GOOGLE_APPLICATION_CREDENTIALS"))


data_folder <- drive_ls(path = "08 Databases + Analysis")

data_path <- "data"
dir.create(data_path) 
## dir.create will fail if folder already exists so not great for scripts on local but as GHA is 
## creating a new environment every time it runs we won't have that problem here
# normally i prefer using fs::dir_create(data_path)
drive_download(file = as_id("1Q8ir4HNvP2zBFwItINhc1rmBvW2MdHnJ-mUULh_Z_oc"), path = paste0("data/cap_database"), overwrite = TRUE)

cap_db <- read_excel("data/cap_database.xlsx", sheet="database")
```


```{r}
kbl(cap_db)
```


